# gui_text.py
TEXTS = {
"title": "LOOKING DB5 工具箱",
"refresh_button": "更新列表",
"record_button_start": "開始錄製",
"record_button_stop": "停止錄製",
"preview_mode_button_recording": "當前：錄製模式",
"preview_mode_button_preview": "當前：預覽模式",
"sync_time_button": "同步時間",
"live_stream_button": "串流網址",
"delete_confirmation_title": "刪除確認",
"delete_confirmation_message": "您確定要刪除此文件嗎？\n",
"error_connection_failed": "連線錯誤",
"error_connection_failed_message": "連接到設備失敗。",
"error_xml_parsing": "XML 解析錯誤",
"success_msg": "成功",
"success_file_deleted_message": "已刪除文件：",
"error_delete_failed_message": "刪除失敗，回傳代碼 ",
"error_file_delete": "無法刪除文件： {}",
"error_msg": "錯誤",
"error_recording_status_message": "無法檢查錄製狀態： ",
"error_toggle_recording_message": "無法切換錄製狀態，請檢查伺服器響應。",
"error_preview_mode_message": "無法檢查預覽模式： ",
"error_toggle_preview_mode_message": "無法切換預覽模式，請檢查伺服器響應。",
"error_sync_time_message": "無法同步時間： ",
"success_sync_time_message": "時間同步成功.\n",
"error_live_stream_url_message": "無法獲取串流網址： ",
"playback_url_text": "回放網址：",
"error_no_preview": "沒有預覽或獲取錯誤",
"copy_url_btn_text": "複製網址",
"tree_index_text": "索引",
"tree_fsize_text": "大小(MB)",
"tree_ftime_text": "時間",
"tree_fname_text": "名稱",
"copy_url_success_msg": "網址已複製到剪貼簿",
}