'''
Note: Paste file's content to gui_text.py to apply the language file!
提示: 將語言檔案的內容貼到gui_text.py來套用!
'''
TEXTS = {
    "title": "LOOKING DB5 工具箱",
    "refresh_button": "更新列表",
    "record_button_start": "開始錄製",
    "record_button_stop": "停止錄製",
    "toggle_mode_button_recording": "錄製模式",
    "toggle_mode_button_review": "檢視模式",
    "toggle_mode_button_photo": "拍照模式",
    "toggle_mode_button_unknown": "未知模式",
    "sync_time_button": "同步時間",
    "live_stream_button": "直播網址",
    "delete_confirmation_title": "刪除確認",
    "delete_confirmation_message": "您確定要刪除此文件嗎？\n",
    "error_connection_failed": "連線錯誤",
    "error_connection_failed_message": "連接到設備失敗。",
    "error_xml_parsing": "XML 解析錯誤",
    "success_msg": "成功",
    "success_file_deleted_message": "刪除文件:",
    "error_delete_failed_message": "刪除失敗，回傳代碼 ",
    "error_file_delete": "刪除文件失敗: {}",
    "error_msg": "錯誤",
    "error_recording_status_message": "獲取錄製狀態失敗: ",
    "error_toggle_recording_message": "切換錄製狀態失敗，請檢查伺服器回應。",
    "error_check_mode_message": "獲取目前模式失敗: ",
    "error_toggle_mode_message": "切換目前模式失敗: ",
    "error_sync_time_message": "同步時間失敗: ",
    "success_sync_time_message": "時間同步成功.\n",
    "error_live_stream_url_message": "獲取直播網址失敗: ",
    "playback_url_text": "回放/下載網址:",
    "playback_url_title": "回放網址",
    "error_no_preview": "沒有預覽或抓取錯誤",
    "copy_url_btn_text": "複製網址",
    "tree_index_text": "索引",
    "tree_fsize_text": "大小(MB)",
    "tree_ftime_text": "時間",
    "tree_fname_text": "名稱",
    "copy_url_success_msg": "網址已複製到剪貼簿",
    "wifi_config_title": "Wi-Fi 設定",
    "wifi_config_ssid": "Wi-Fi SSID:",
    "wifi_config_password": "Wi-Fi 密碼:",
    "wifi_config_reveal_btn": "顯示/隱藏字母",
    "wifi_config_note_label": "密碼需至少 8 個字元！\n\n請使用英文、數字、\n底線 (_) 或短槓 (-) 等符號\n來定義 Wi-Fi 名稱和密碼\n以確保設定成功。",
    "error_wifi_config_ssid": "傳送 Wi-Fi SSID 失敗",
    "error_wifi_config_password": "傳送 Wi-Fi 密碼失敗",
    "error_wifi_len_password": "密碼長度不符",
    "wifi_config_btn": "Wi-Fi 設定",
    "wifi_config_send_btn": "傳送 Wi-Fi 設定",
    "wifi_config_setup_success": "Wi-Fi 設定已成功傳送！",
    "wifi_config_restart_success": "裝置 Wi-Fi 已成功重新啟動！",
    "error_wifi_config_restart": "重新啟動裝置 Wi-Fi 失敗",
    "wifi_config_restart_btn": "重新啟動裝置 Wi-Fi",
    "take_pic_success": "拍照成功！",
    "take_pic_btn": "拍照",
    "error_take_pic": "拍照失敗。",
}
