# gui_text.py
TEXTS = {
    "title": "LOOKING DB5 Toolbox",
    "refresh_button": "Refresh List",
    "record_button_start": "Start Recording",
    "record_button_stop": "Stop Recording",
    "preview_mode_button_recording": "is Recording mode",
    "preview_mode_button_preview": "is Preview mode",
    "sync_time_button": "Sync time",
    "live_stream_button": "Live stream URL",
    "delete_confirmation_title": "Delete Confirmation",
    "delete_confirmation_message": "Are you sure you want to delete this file?\n",
    "error_connection_failed": "Connection Error",
    "error_connection_failed_message": "Connection to device failed.",
    "error_xml_parsing": "XML parsing error",
    "success_msg": "Success",
    "success_file_deleted_message": "File deleted:",
    "error_delete_failed_message": "Deletion failed, return code ",
    "error_file_delete": "Failed to delete file: {}",
    "error_msg": "Error",
    "error_recording_status_message": "Failed to check recording status: ",
    "error_toggle_recording_message": "Failed to toggle recording status, please check server response.",
    "error_preview_mode_message": "Failed to check preview mode: ",
    "error_toggle_preview_mode_message": "Failed to toggle preview mode, please check server response.",
    "error_sync_time_message": "Failed to synchronize time: ",
    "success_sync_time_message": "Time synchronized successfully.\n",
    "error_live_stream_url_message": "Failed to get live stream URL: ",
    "playback_url_text": "Playback URL:",
    "error_no_preview": "No preview or fetch ERROR",
    "copy_url_btn_text": "Copy URL",
    "tree_index_text": "Index",
    "tree_fsize_text": "Size(MB)",
    "tree_ftime_text": "Time",
    "tree_fname_text": "Name",
    "copy_url_success_msg": "URL copied to clipboard",
}