'''
Note: Paste file's content to gui_text.py to apply the language file!
提示: 將語言檔案的內容貼到gui_text.py來套用!
'''
TEXTS = {
    "title": "LOOKING DB5 Toolbox",
    "refresh_button": "Refresh List",
    "record_button_start": "Start Recording",
    "record_button_stop": "Stop Recording",
    "toggle_mode_button_recording": "Recording mode",
    "toggle_mode_button_review": "Review mode",
    "toggle_mode_button_photo": "Photo mode",
    "toggle_mode_button_unknown": "Unknown mode",
    "sync_time_button": "Sync time",
    "live_stream_button": "Live stream URL",
    "delete_confirmation_title": "Delete Confirmation",
    "delete_confirmation_message": "Are you sure you want to delete this file?\n",
    "error_connection_failed": "Connection Error",
    "error_connection_failed_message": "Connection to device failed.",
    "error_xml_parsing": "XML parsing error",
    "success_msg": "Success",
    "success_file_deleted_message": "File deleted:",
    "error_delete_failed_message": "Deletion failed, return code ",
    "error_file_delete": "Failed to delete file: {}",
    "error_msg": "Error",
    "error_recording_status_message": "Failed to check recording status: ",
    "error_toggle_recording_message": "Failed to toggle recording status, please check server response.",
    "error_check_mode_message": "Failed to check current mode: ",
    "error_toggle_mode_message": "Failed to toggle current mode: ",
    "error_sync_time_message": "Failed to synchronize time: ",
    "success_sync_time_message": "Time synchronized successfully.\n",
    "error_live_stream_url_message": "Failed to get live stream URL: ",
    "playback_url_text": "Playback/Download URL:",
    "playback_url_title": "Playback URL",
    "error_no_preview": "No preview or fetch ERROR",
    "copy_url_btn_text": "Copy URL",
    "tree_index_text": "Index",
    "tree_fsize_text": "Size(MB)",
    "tree_ftime_text": "Time",
    "tree_fname_text": "Name",
    "copy_url_success_msg": "URL copied to clipboard",
    "wifi_config_title": "Wi-Fi Config",
    "wifi_config_ssid": "Wi-Fi SSID:",
    "wifi_config_password": "Wi-Fi Password:",
    "wifi_config_reveal_btn": "Reveal/Hidden Letter",
    "wifi_config_note_label": "Password need 8 charters or more! \n\nUse English characters, numbers, \ncommon symbols like '_' or '-' \nto define Wi-Fi name and password \nto ensure setup success.",
    "error_wifi_config_ssid": "Failed to send Wi-Fi SSID",
    "error_wifi_config_password": "Failed to send Wi-Fi Password",
    "error_wifi_len_password": "Password length not match",
    "wifi_config_btn": "Wi-Fi Config",
    "wifi_config_send_btn": "Send Wi-Fi Config",
    "wifi_config_setup_success": "Wi-Fi configuration sent successfully!",
    "wifi_config_restart_success": "Device Wi-Fi restarted successfully!",
    "error_wifi_config_restart": "Failed to restart device Wi-Fi",
    "wifi_config_restart_btn": "Restart Device Wi-Fi",
    "take_pic_success": "Picture taken successfully!",
    "take_pic_btn": "Take Picture",
    "error_take_pic": "Failed to take picture.",
    "del_refresh_on": "Refresh after delete ON",
    "del_refresh_off": "Refresh after delete OFF",
}
